map.set("Absorb",["Absorb","Grass","20","100%","20","User recovers 50% of the damage dealt.","O"])
map.set("Acid",["Acid","Poison","40","100%","30","10% chance to lower the foe(s) Defense by 1.","O"])
map.set("Acid Armor",["Acid Armor","Poison","—","—","40","Raises the user's Defense by 2.","O"])
map.set("Aerial Ace",["Aerial Ace","Flying","60","—","20","This move does not check accuracy.","O"])
map.set("Aeroblast",["Aeroblast","Flying","100","95%","5","High critical hit ratio.","O"])
map.set("Agility",["Agility","Psychic","—","—","30","Raises the user's Speed by 2.","O"])
map.set("Air Cutter",["Air Cutter","Flying","55","95%","25","High critical hit ratio. Hits adjacent foes.","O"])
map.set("Amnesia",["Amnesia","Psychic","—","—","20","Raises the user's Sp. Def by 2.","O"])
map.set("Ancient Power",["Ancient Power","Rock","60","100%","5","10% chance to raise all stats by 1 (not acc/eva).","O"])
map.set("Arm Thrust",["Arm Thrust","Fighting","15","100%","20","Hits 2-5 times in one turn.","O"])
map.set("Aromatherapy",["Aromatherapy","Grass","—","—","5","Cures the user's party of all status conditions.","O"])
map.set("Assist",["Assist","Normal","—","—","20","Uses a random move known by a team member.","O"])
map.set("Astonish",["Astonish","Ghost","30","100%","15","30% chance to make the target flinch.","O"])
map.set("Attract",["Attract","Normal","—","100%","15","A target of the opposite gender gets infatuated.","O"])
map.set("Aurora Beam",["Aurora Beam","Ice","65","100%","20","10% chance to lower the target's Attack by 1.","O"])
map.set("Barrage",["Barrage","Normal","15","85%","20","Hits 2-5 times in one turn.","O"])
map.set("Barrier",["Barrier","Psychic","—","—","30","Raises the user's Defense by 2.","O"])
map.set("Baton Pass",["Baton Pass","Normal","—","—","40","User switches, passing stat changes and more.","O"])
map.set("Beat Up",["Beat Up","Dark","10","100%","10","All healthy allies aid in damaging the target.","O"])
map.set("Belly Drum",["Belly Drum","Normal","—","—","10","User loses 50% max HP. Maximizes Attack.","O"])
map.set("Bide",["Bide","Normal","—","100%","10","Waits 2 turns; deals double the damage taken.","O"])
map.set("Bind",["Bind","Normal","15","75%","20","Traps and damages the target for 2-5 turns.","O"])
map.set("Bite",["Bite","Dark","60","100%","25","30% chance to make the target flinch.","O"])
map.set("Blast Burn",["Blast Burn","Fire","150","90%","5","User cannot move next turn.","O"])
map.set("Blaze Kick",["Blaze Kick","Fire","85","90%","10","High critical hit ratio. 10% chance to burn.","O"])
map.set("Blizzard",["Blizzard","Ice","120","70%","5","10% chance to freeze foe(s).","O"])
map.set("Block",["Block","Normal","—","—","5","Prevents the target from switching out.","O"])
map.set("Body Slam",["Body Slam","Normal","85","100%","15","30% chance to paralyze the target.","O"])
map.set("Bone Club",["Bone Club","Ground","65","85%","20","10% chance to make the target flinch.","O"])
map.set("Bone Rush",["Bone Rush","Ground","25","80%","10","Hits 2-5 times in one turn.","O"])
map.set("Bonemerang",["Bonemerang","Ground","50","90%","10","Hits 2 times in one turn.","O"])
map.set("Bounce",["Bounce","Flying","85","85%","5","Bounces turn 1. Hits turn 2. 30% paralyze.","O"])
map.set("Brick Break",["Brick Break","Fighting","75","100%","15","Destroys screens, even if the target is immune.","O"])
map.set("Bubble",["Bubble","Water","20","100%","30","10% chance to lower the foe(s) Speed by 1.","O"])
map.set("Bubble Beam",["Bubble Beam","Water","65","100%","20","10% chance to lower the target's Speed by 1.","O"])
map.set("Bulk Up",["Bulk Up","Fighting","—","—","20","Raises the user's Attack and Defense by 1.","O"])
map.set("Bullet Seed",["Bullet Seed","Grass","10","100%","30","Hits 2-5 times in one turn.","O"])
map.set("Calm Mind",["Calm Mind","Psychic","—","—","20","Raises the user's Sp. Atk and Sp. Def by 1.","O"])
map.set("Camouflage",["Camouflage","Normal","—","—","20","Changes user's type based on terrain. (Normal)","O"])
map.set("Charge",["Charge","Electric","—","—","20","The user's Electric attack next turn has 2x power.","O"])
map.set("Charm",["Charm","Normal","—","100%","20","Lowers the target's Attack by 2.","O"])
map.set("Clamp",["Clamp","Water","35","75%","10","Traps and damages the target for 2-5 turns.","O"])
map.set("Comet Punch",["Comet Punch","Normal","18","85%","15","Hits 2-5 times in one turn.","O"])
map.set("Confuse Ray",["Confuse Ray","Ghost","—","100%","10","Confuses the target.","O"])
map.set("Confusion",["Confusion","Psychic","50","100%","25","10% chance to confuse the target.","O"])
map.set("Constrict",["Constrict","Normal","10","100%","35","10% chance to lower the target's Speed by 1.","O"])
map.set("Conversion",["Conversion","Normal","—","—","30","Changes user's type to match a known move.","O"])
map.set("Conversion 2",["Conversion 2","Normal","—","—","30","User's type changes to resist last move against it.","O"])
map.set("Cosmic Power",["Cosmic Power","Psychic","—","—","20","Raises the user's Defense and Sp. Def by 1.","O"])
map.set("Cotton Spore",["Cotton Spore","Grass","—","85%","40","Lowers the target's Speed by 2.","O"])
map.set("Counter",["Counter","Fighting","—","100%","20","If hit by physical attack, returns double damage.","O"])
map.set("Covet",["Covet","Normal","40","100%","40","If the user has no item, it steals the target's.","O"])
map.set("Crabhammer",["Crabhammer","Water","90","85%","10","High critical hit ratio.","O"])
map.set("Cross Chop",["Cross Chop","Fighting","100","80%","5","High critical hit ratio.","O"])
map.set("Crunch",["Crunch","Dark","80","100%","15","20% chance to lower the target's Sp. Def by 1.","O"])
map.set("Crush Claw",["Crush Claw","Normal","75","95%","10","50% chance to lower the target's Defense by 1.","O"])
map.set("Curse",["Curse","Normal","—","—","10","Curses if Ghost, else -1 Spe, +1 Atk, +1 Def.","O"])
map.set("Cut",["Cut","Normal","50","95%","30","No additional effect.","O"])
map.set("Defense Curl",["Defense Curl","Normal","—","—","40","Raises the user's Defense by 1.","O"])
map.set("Destiny Bond",["Destiny Bond","Ghost","—","—","5","If an opponent knocks out the user, it also faints.","O"])
map.set("Detect",["Detect","Fighting","—","—","5","Prevents moves from affecting the user this turn.","O"])
map.set("Dig",["Dig","Ground","60","100%","10","Digs underground turn 1, strikes turn 2.","O"])
map.set("Disable",["Disable","Normal","—","55%","20","For 2-5 turns, disables the target's last move.","O"])
map.set("Dive",["Dive","Water","60","100%","10","Dives underwater turn 1, strikes turn 2.","O"])
map.set("Dizzy Punch",["Dizzy Punch","Normal","70","100%","10","20% chance to confuse the target.","O"])
map.set("Doom Desire",["Doom Desire","Steel","120","85%","5","Hits two turns after being used.","O"])
map.set("Double Kick",["Double Kick","Fighting","30","100%","30","Hits 2 times in one turn.","O"])
map.set("Double Slap",["Double Slap","Normal","15","85%","10","Hits 2-5 times in one turn.","O"])
map.set("Double Team",["Double Team","Normal","—","—","15","Raises the user's evasiveness by 1.","O"])
map.set("Double-Edge",["Double-Edge","Normal","120","100%","15","Has 1/3 recoil.","O"])
map.set("Dragon Breath",["Dragon Breath","Dragon","60","100%","20","30% chance to paralyze the target.","O"])
map.set("Dragon Claw",["Dragon Claw","Dragon","80","100%","15","No additional effect.","O"])
map.set("Dragon Dance",["Dragon Dance","Dragon","—","—","20","Raises the user's Attack and Speed by 1.","O"])
map.set("Dragon Rage",["Dragon Rage","Dragon","—","100%","10","Deals 40 HP of damage to the target.","O"])
map.set("Dream Eater",["Dream Eater","Psychic","100","100%","15","User gains 1/2 HP inflicted. Sleeping target only.","O"])
map.set("Drill Peck",["Drill Peck","Flying","80","100%","20","No additional effect.","O"])
map.set("Dynamic Punch",["Dynamic Punch","Fighting","100","50%","5","100% chance to confuse the target.","O"])
map.set("Earthquake",["Earthquake","Ground","100","100%","10","Hits adjacent Pokemon. Power doubles on Dig.","O"])
map.set("Egg Bomb",["Egg Bomb","Normal","100","75%","10","No additional effect.","O"])
map.set("Ember",["Ember","Fire","40","100%","25","10% chance to burn the target.","O"])
map.set("Encore",["Encore","Normal","—","100%","5","The target repeats its last move for 3-6 turns.","O"])
map.set("Endeavor",["Endeavor","Normal","—","100%","5","Lowers the target's HP to the user's HP.","O"])
map.set("Endure",["Endure","Normal","—","—","10","User survives attacks this turn with at least 1 HP.","O"])
map.set("Eruption",["Eruption","Fire","150","100%","5","Less power as user's HP decreases. Hits foe(s).","O"])
map.set("Explosion",["Explosion","Normal","250","100%","5","Target's Def halved during damage. User faints.","O"])
map.set("Extrasensory",["Extrasensory","Psychic","80","100%","30","10% chance to make the target flinch.","O"])
map.set("Extreme Speed",["Extreme Speed","Normal","80","100%","5","Usually goes first.","O"])
map.set("Facade",["Facade","Normal","70","100%","20","Power doubles if user is burn/poison/paralyzed.","O"])
map.set("Fake Out",["Fake Out","Normal","40","100%","10","Hits first. First turn out only. 100% flinch chance.","O"])
map.set("Fake Tears",["Fake Tears","Dark","—","100%","20","Lowers the target's Sp. Def by 2.","O"])
map.set("False Swipe",["False Swipe","Normal","40","100%","40","Always leaves the target with at least 1 HP.","O"])
map.set("Feather Dance",["Feather Dance","Flying","—","100%","15","Lowers the target's Attack by 2.","O"])
map.set("Feint Attack",["Feint Attack","Dark","60","—","20","This move does not check accuracy.","O"])
map.set("Fire Blast",["Fire Blast","Fire","120","85%","5","10% chance to burn the target.","O"])
map.set("Fire Punch",["Fire Punch","Fire","75","100%","15","10% chance to burn the target.","O"])
map.set("Fire Spin",["Fire Spin","Fire","15","70%","15","Traps and damages the target for 2-5 turns.","O"])
map.set("Fissure",["Fissure","Ground","—","30%","5","OHKOs the target. Fails if user is a lower level.","O"])
map.set("Flail",["Flail","Normal","—","100%","15","More power the less HP the user has left.","O"])
map.set("Flame Wheel",["Flame Wheel","Fire","60","100%","25","10% chance to burn the target. Thaws user.","O"])
map.set("Flamethrower",["Flamethrower","Fire","95","100%","15","10% chance to burn the target.","O"])
map.set("Flash",["Flash","Normal","—","70%","20","Lowers the target's accuracy by 1.","O"])
map.set("Flatter",["Flatter","Dark","—","100%","15","Raises the target's Sp. Atk by 1 and confuses it.","O"])
map.set("Fly",["Fly","Flying","70","95%","15","Flies up on first turn, then strikes the next turn.","O"])
map.set("Focus Energy",["Focus Energy","Normal","—","—","30","Raises the user's critical hit ratio by 2.","O"])
map.set("Focus Punch",["Focus Punch","Fighting","150","100%","20","Fails if the user takes damage before it hits.","O"])
map.set("Follow Me",["Follow Me","Normal","—","—","20","The foes' moves target the user on the turn used.","O"])
map.set("Foresight",["Foresight","Normal","—","100%","40","Fighting, Normal hit Ghost. Evasiveness ignored.","O"])
map.set("Frenzy Plant",["Frenzy Plant","Grass","150","90%","5","User cannot move next turn.","O"])
map.set("Frustration",["Frustration","Normal","—","100%","20","Max 102 power at minimum Happiness.","O"])
map.set("Fury Attack",["Fury Attack","Normal","15","85%","20","Hits 2-5 times in one turn.","O"])
map.set("Fury Cutter",["Fury Cutter","Bug","10","95%","20","Power doubles with each hit, up to 160.","O"])
map.set("Fury Swipes",["Fury Swipes","Normal","18","80%","15","Hits 2-5 times in one turn.","O"])
map.set("Future Sight",["Future Sight","Psychic","80","90%","15","Hits two turns after being used.","O"])
map.set("Giga Drain",["Giga Drain","Grass","60","100%","5","User recovers 50% of the damage dealt.","O"])
map.set("Glare",["Glare","Normal","—","75%","30","Paralyzes the target.","O"])
map.set("Grass Whistle",["Grass Whistle","Grass","—","55%","15","Causes the target to fall asleep.","O"])
map.set("Growl",["Growl","Normal","—","100%","40","Lowers the foe(s) Attack by 1.","O"])
map.set("Growth",["Growth","Normal","—","—","40","Raises the user's Sp. Atk by 1.","O"])
map.set("Grudge",["Grudge","Ghost","—","—","5","If the user faints, the attack used loses all its PP.","O"])
map.set("Guillotine",["Guillotine","Normal","—","30%","5","OHKOs the target. Fails if user is a lower level.","O"])
map.set("Gust",["Gust","Flying","40","100%","35","Power doubles during Bounce and Fly.","O"])
map.set("Hail",["Hail","Ice","—","—","10","For 5 turns, hail crashes down.","O"])
map.set("Harden",["Harden","Normal","—","—","30","Raises the user's Defense by 1.","O"])
map.set("Haze",["Haze","Ice","—","—","30","Eliminates all stat changes.","O"])
map.set("Headbutt",["Headbutt","Normal","70","100%","15","30% chance to make the target flinch.","O"])
map.set("Heal Bell",["Heal Bell","Normal","—","—","5","Cures the user's party of all status conditions.","O"])
map.set("Heat Wave",["Heat Wave","Fire","100","90%","10","10% chance to burn the foe(s).","O"])
map.set("Helping Hand",["Helping Hand","Normal","—","—","20","One adjacent ally's move power is 1.5x this turn.","O"])
map.set("Hidden Power",["Hidden Power","Normal","—","100%","15","Varies in power and type based on the user's IVs.","O"])
map.set("High Jump Kick",["High Jump Kick","Fighting","85","90%","20","If miss, user takes 1/2 damage it would've dealt.","O"])
map.set("Horn Attack",["Horn Attack","Normal","65","100%","25","No additional effect.","O"])
map.set("Horn Drill",["Horn Drill","Normal","—","30%","5","OHKOs the target. Fails if user is a lower level.","O"])
map.set("Howl",["Howl","Normal","—","—","40","Raises the user's Attack by 1.","O"])
map.set("Hydro Cannon",["Hydro Cannon","Water","150","90%","5","User cannot move next turn.","O"])
map.set("Hydro Pump",["Hydro Pump","Water","120","80%","5","No additional effect.","O"])
map.set("Hyper Beam",["Hyper Beam","Normal","150","90%","5","User cannot move next turn.","O"])
map.set("Hyper Fang",["Hyper Fang","Normal","80","90%","15","10% chance to make the target flinch.","O"])
map.set("Hyper Voice",["Hyper Voice","Normal","90","100%","10","No additional effect. Hits adjacent foes.","O"])
map.set("Hypnosis",["Hypnosis","Psychic","—","60%","20","Causes the target to fall asleep.","O"])
map.set("Ice Ball",["Ice Ball","Ice","30","90%","20","Power doubles with each hit. Repeats for 5 turns.","O"])
map.set("Ice Beam",["Ice Beam","Ice","95","100%","10","10% chance to freeze the target.","O"])
map.set("Ice Punch",["Ice Punch","Ice","75","100%","15","10% chance to freeze the target.","O"])
map.set("Icicle Spear",["Icicle Spear","Ice","10","100%","30","Hits 2-5 times in one turn.","O"])
map.set("Icy Wind",["Icy Wind","Ice","55","95%","15","100% chance to lower the foe(s) Speed by 1.","O"])
map.set("Imprison",["Imprison","Psychic","—","—","10","No foe can use any move known by the user.","O"])
map.set("Ingrain",["Ingrain","Grass","—","—","20","User recovers 1/16 max HP per turn. Traps user.","O"])
map.set("Iron Defense",["Iron Defense","Steel","—","—","15","Raises the user's Defense by 2.","O"])
map.set("Iron Tail",["Iron Tail","Steel","100","75%","15","30% chance to lower the target's Defense by 1.","O"])
map.set("Jump Kick",["Jump Kick","Fighting","70","95%","25","If miss, user takes 1/2 damage it would've dealt.","O"])
map.set("Karate Chop",["Karate Chop","Fighting","50","100%","25","High critical hit ratio.","O"])
map.set("Kinesis",["Kinesis","Psychic","—","80%","15","Lowers the target's accuracy by 1.","O"])
map.set("Knock Off",["Knock Off","Dark","20","100%","20","Target's item is lost and it cannot obtain another.","O"])
map.set("Leaf Blade",["Leaf Blade","Grass","70","100%","15","High critical hit ratio.","O"])
map.set("Leech Life",["Leech Life","Bug","20","100%","15","User recovers 50% of the damage dealt.","O"])
map.set("Leech Seed",["Leech Seed","Grass","—","90%","10","1/8 of target's HP is restored to user every turn.","O"])
map.set("Leer",["Leer","Normal","—","100%","30","Lowers the foe(s) Defense by 1.","O"])
map.set("Lick",["Lick","Ghost","20","100%","30","30% chance to paralyze the target.","O"])
map.set("Light Screen",["Light Screen","Psychic","—","—","30","For 5 turns, special damage to allies is halved.","O"])
map.set("Lock-On",["Lock-On","Normal","—","100%","5","User's next move will not miss the target.","O"])
map.set("Lovely Kiss",["Lovely Kiss","Normal","—","75%","10","Causes the target to fall asleep.","O"])
map.set("Low Kick",["Low Kick","Fighting","—","100%","20","More power the heavier the target.","O"])
map.set("Luster Purge",["Luster Purge","Psychic","70","100%","5","50% chance to lower the target's Sp. Def by 1.","O"])
map.set("Mach Punch",["Mach Punch","Fighting","40","100%","30","Usually goes first.","O"])
map.set("Magic Coat",["Magic Coat","Psychic","—","—","15","Bounces back certain non-damaging moves.","O"])
map.set("Magical Leaf",["Magical Leaf","Grass","60","—","20","This move does not check accuracy.","O"])
map.set("Magnitude",["Magnitude","Ground","—","100%","30","Hits adjacent Pokemon. Power varies; 2x on Dig.","O"])
map.set("Mean Look",["Mean Look","Normal","—","—","5","Prevents the target from switching out.","O"])
map.set("Meditate",["Meditate","Psychic","—","—","40","Raises the user's Attack by 1.","O"])
map.set("Mega Drain",["Mega Drain","Grass","40","100%","10","User recovers 50% of the damage dealt.","O"])
map.set("Mega Kick",["Mega Kick","Normal","120","75%","5","No additional effect.","O"])
map.set("Mega Punch",["Mega Punch","Normal","80","85%","20","No additional effect.","O"])
map.set("Megahorn",["Megahorn","Bug","120","85%","10","No additional effect.","O"])
map.set("Memento",["Memento","Dark","—","—","10","Lowers target's Attack, Sp. Atk by 2. User faints.","O"])
map.set("Metal Claw",["Metal Claw","Steel","50","95%","35","10% chance to raise the user's Attack by 1.","O"])
map.set("Metal Sound",["Metal Sound","Steel","—","85%","40","Lowers the target's Sp. Def by 2.","O"])
map.set("Meteor Mash",["Meteor Mash","Steel","100","85%","10","20% chance to raise the user's Attack by 1.","O"])
map.set("Metronome",["Metronome","Normal","—","—","10","Picks a random move.","O"])
map.set("Milk Drink",["Milk Drink","Normal","—","—","10","Heals the user by 50% of its max HP.","O"])
map.set("Mimic",["Mimic","Normal","—","—","10","The last move the target used replaces this one.","O"])
map.set("Mind Reader",["Mind Reader","Normal","—","100%","5","User's next move will not miss the target.","O"])
map.set("Minimize",["Minimize","Normal","—","—","20","Raises the user's evasiveness by 1.","O"])
map.set("Mirror Coat",["Mirror Coat","Psychic","—","100%","20","If hit by special attack, returns double damage.","O"])
map.set("Mirror Move",["Mirror Move","Flying","—","—","20","User uses the target's last used move against it.","O"])
map.set("Mist",["Mist","Ice","—","—","30","For 5 turns, protects user's party from stat drops.","O"])
map.set("Mist Ball",["Mist Ball","Psychic","70","100%","5","50% chance to lower the target's Sp. Atk by 1.","O"])
map.set("Moonlight",["Moonlight","Normal","—","—","5","Heals the user by a weather-dependent amount.","O"])
map.set("Morning Sun",["Morning Sun","Normal","—","—","5","Heals the user by a weather-dependent amount.","O"])
map.set("Mud Shot",["Mud Shot","Ground","55","95%","15","100% chance to lower the target's Speed by 1.","O"])
map.set("Mud Sport",["Mud Sport","Ground","—","—","15","Weakens Electric-type attacks to 1/2 their power.","O"])
map.set("Mud-Slap",["Mud-Slap","Ground","20","100%","10","100% chance to lower the target's accuracy by 1.","O"])
map.set("Muddy Water",["Muddy Water","Water","95","85%","10","30% chance to lower the foe(s) accuracy by 1.","O"])
map.set("Nature Power",["Nature Power","Normal","—","95%","20","Attack changes based on terrain. (Swift)","O"])
map.set("Needle Arm",["Needle Arm","Grass","60","100%","15","30% chance to make the target flinch.","O"])
map.set("Night Shade",["Night Shade","Ghost","—","100%","15","Does damage equal to the user's level.","O"])
map.set("Nightmare",["Nightmare","Ghost","—","—","15","A sleeping target is hurt by 1/4 max HP per turn.","O"])
map.set("Octazooka",["Octazooka","Water","65","85%","10","50% chance to lower the target's accuracy by 1.","O"])
map.set("Odor Sleuth",["Odor Sleuth","Normal","—","100%","40","Fighting, Normal hit Ghost. Evasiveness ignored.","O"])
map.set("Outrage",["Outrage","Dragon","90","100%","15","Lasts 2-3 turns. Confuses the user afterwards.","O"])
map.set("Overheat",["Overheat","Fire","140","90%","5","Lowers the user's Sp. Atk by 2.","O"])
map.set("Pain Split",["Pain Split","Normal","—","—","20","Shares HP of user and target equally.","O"])
map.set("Pay Day",["Pay Day","Normal","40","100%","20","Scatters coins.","O"])
map.set("Peck",["Peck","Flying","35","100%","35","No additional effect.","O"])
map.set("Perish Song",["Perish Song","Normal","—","—","5","All active Pokemon will faint in 3 turns.","O"])
map.set("Petal Dance",["Petal Dance","Grass","70","100%","20","Lasts 2-3 turns. Confuses the user afterwards.","O"])
map.set("Pin Missile",["Pin Missile","Bug","14","85%","20","Hits 2-5 times in one turn.","O"])
map.set("Poison Fang",["Poison Fang","Poison","50","100%","15","30% chance to badly poison the target.","O"])
map.set("Poison Gas",["Poison Gas","Poison","—","55%","40","Poisons the foe(s).","O"])
map.set("Poison Powder",["Poison Powder","Poison","—","75%","35","Poisons the target.","O"])
map.set("Poison Sting",["Poison Sting","Poison","15","100%","35","30% chance to poison the target.","O"])
map.set("Poison Tail",["Poison Tail","Poison","50","100%","25","High critical hit ratio. 10% chance to poison.","O"])
map.set("Pound",["Pound","Normal","40","100%","35","No additional effect.","O"])
map.set("Powder Snow",["Powder Snow","Ice","40","100%","25","10% chance to freeze the foe(s).","O"])
map.set("Present",["Present","Normal","—","90%","15","40, 80, 120 power, or heals target 1/4 max HP.","O"])
map.set("Protect",["Protect","Normal","—","—","10","Prevents moves from affecting the user this turn.","O"])
map.set("Psybeam",["Psybeam","Psychic","65","100%","20","10% chance to confuse the target.","O"])
map.set("Psych Up",["Psych Up","Normal","—","—","10","Copies the target's current stat stages.","O"])
map.set("Psychic",["Psychic","Psychic","90","100%","10","10% chance to lower the target's Sp. Def by 1.","O"])
map.set("Psycho Boost",["Psycho Boost","Psychic","140","90%","5","Lowers the user's Sp. Atk by 2.","O"])
map.set("Psywave",["Psywave","Psychic","—","80%","15","Random damage equal to 0.5x-1.5x user's level.","O"])
map.set("Pursuit",["Pursuit","Dark","40","100%","20","Power doubles if the targeted foe is switching out.","O"])
map.set("Quick Attack",["Quick Attack","Normal","40","100%","30","Usually goes first.","O"])
map.set("Rage",["Rage","Normal","20","100%","20","Raises the user's Attack by 1 if hit during use.","O"])
map.set("Rain Dance",["Rain Dance","Water","—","—","5","For 5 turns, heavy rain powers Water moves.","O"])
map.set("Rapid Spin",["Rapid Spin","Normal","20","100%","40","Frees user from hazards, binding, Leech Seed.","O"])
map.set("Razor Leaf",["Razor Leaf","Grass","55","95%","25","High critical hit ratio. Hits adjacent foes.","O"])
map.set("Razor Wind",["Razor Wind","Normal","80","100%","10","Charges, then hits foe(s) turn 2.","O"])
map.set("Recover",["Recover","Normal","—","—","20","Heals the user by 50% of its max HP.","O"])
map.set("Recycle",["Recycle","Normal","—","—","10","Restores the item the user last used.","O"])
map.set("Reflect",["Reflect","Psychic","—","—","20","For 5 turns, physical damage to allies is halved.","O"])
map.set("Refresh",["Refresh","Normal","—","—","20","User cures its burn, poison, or paralysis.","O"])
map.set("Rest",["Rest","Psychic","—","—","10","User sleeps 2 turns and restores HP and status.","O"])
map.set("Return",["Return","Normal","—","100%","20","Max 102 power at maximum Happiness.","O"])
map.set("Revenge",["Revenge","Fighting","60","100%","10","Damage doubles if user is hit by the target.","O"])
map.set("Reversal",["Reversal","Fighting","—","100%","15","More power the less HP the user has left.","O"])
map.set("Roar",["Roar","Normal","—","100%","20","Forces the target to switch to a random ally.","O"])
map.set("Rock Blast",["Rock Blast","Rock","25","80%","10","Hits 2-5 times in one turn.","O"])
map.set("Rock Slide",["Rock Slide","Rock","75","90%","10","30% chance to make the foe(s) flinch.","O"])
map.set("Rock Smash",["Rock Smash","Fighting","20","100%","15","50% chance to lower the target's Defense by 1.","O"])
map.set("Rock Throw",["Rock Throw","Rock","50","90%","15","No additional effect.","O"])
map.set("Rock Tomb",["Rock Tomb","Rock","50","80%","10","100% chance to lower the target's Speed by 1.","O"])
map.set("Role Play",["Role Play","Psychic","—","—","10","User replaces its Ability with the target's.","O"])
map.set("Rolling Kick",["Rolling Kick","Fighting","60","85%","15","30% chance to make the target flinch.","O"])
map.set("Rollout",["Rollout","Rock","30","90%","20","Power doubles with each hit. Repeats for 5 turns.","O"])
map.set("Sacred Fire",["Sacred Fire","Fire","100","95%","5","50% chance to burn the target. Thaws user.","O"])
map.set("Safeguard",["Safeguard","Normal","—","—","25","For 5 turns, protects user's party from status.","O"])
map.set("Sand Attack",["Sand Attack","Ground","—","100%","15","Lowers the target's accuracy by 1.","O"])
map.set("Sand Tomb",["Sand Tomb","Ground","15","70%","15","Traps and damages the target for 2-5 turns.","O"])
map.set("Sandstorm",["Sandstorm","Rock","—","—","10","For 5 turns, a sandstorm rages.","O"])
map.set("Scary Face",["Scary Face","Normal","—","90%","10","Lowers the target's Speed by 2.","O"])
map.set("Scratch",["Scratch","Normal","40","100%","35","No additional effect.","O"])
map.set("Screech",["Screech","Normal","—","85%","40","Lowers the target's Defense by 2.","O"])
map.set("Secret Power",["Secret Power","Normal","70","100%","20","Effect varies with terrain. (30% paralysis chance)","O"])
map.set("Seismic Toss",["Seismic Toss","Fighting","—","100%","20","Does damage equal to the user's level.","O"])
map.set("Self-Destruct",["Self-Destruct","Normal","200","100%","5","Target's Def halved during damage. User faints.","O"])
map.set("Shadow Ball",["Shadow Ball","Ghost","80","100%","15","20% chance to lower the target's Sp. Def by 1.","O"])
map.set("Shadow Punch",["Shadow Punch","Ghost","60","—","20","This move does not check accuracy.","O"])
map.set("Sharpen",["Sharpen","Normal","—","—","30","Raises the user's Attack by 1.","O"])
map.set("Sheer Cold",["Sheer Cold","Ice","—","30%","5","OHKOs the target. Fails if user is a lower level.","O"])
map.set("Shock Wave",["Shock Wave","Electric","60","—","20","This move does not check accuracy.","O"])
map.set("Signal Beam",["Signal Beam","Bug","75","100%","15","10% chance to confuse the target.","O"])
map.set("Silver Wind",["Silver Wind","Bug","60","100%","5","10% chance to raise all stats by 1 (not acc/eva).","O"])
map.set("Sing",["Sing","Normal","—","55%","15","Causes the target to fall asleep.","O"])
map.set("Sketch",["Sketch","Normal","—","—","1","Permanently copies the last move target used.","O"])
map.set("Skill Swap",["Skill Swap","Psychic","—","—","10","The user and the target trade Abilities.","O"])
map.set("Skull Bash",["Skull Bash","Normal","100","100%","15","Raises user's Defense by 1 on turn 1. Hits turn 2.","O"])
map.set("Sky Attack",["Sky Attack","Flying","140","90%","5","Charges, then hits turn 2. 30% flinch. High crit.","O"])
map.set("Sky Uppercut",["Sky Uppercut","Fighting","85","90%","15","Can hit Pokemon using Bounce or Fly.","O"])
map.set("Slack Off",["Slack Off","Normal","—","—","10","Heals the user by 50% of its max HP.","O"])
map.set("Slam",["Slam","Normal","80","75%","20","No additional effect.","O"])
map.set("Slash",["Slash","Normal","70","100%","20","High critical hit ratio.","O"])
map.set("Sleep Powder",["Sleep Powder","Grass","—","75%","15","Causes the target to fall asleep.","O"])
map.set("Sleep Talk",["Sleep Talk","Normal","—","—","10","User must be asleep. Uses another known move.","O"])
map.set("Sludge",["Sludge","Poison","65","100%","20","30% chance to poison the target.","O"])
map.set("Sludge Bomb",["Sludge Bomb","Poison","90","100%","10","30% chance to poison the target.","O"])
map.set("Smelling Salts",["Smelling Salts","Normal","60","100%","10","Damage doubles if target is paralyzed; cures it.","O"])
map.set("Smog",["Smog","Poison","20","70%","20","40% chance to poison the target.","O"])
map.set("Smokescreen",["Smokescreen","Normal","—","100%","20","Lowers the target's accuracy by 1.","O"])
map.set("Snatch",["Snatch","Dark","—","—","10","User steals certain support moves to use itself.","O"])
map.set("Snore",["Snore","Normal","40","100%","15","User must be asleep. 30% chance to flinch target.","O"])
map.set("Soft-Boiled",["Soft-Boiled","Normal","—","—","10","Heals the user by 50% of its max HP.","O"])
map.set("Solar Beam",["Solar Beam","Grass","120","100%","10","Charges turn 1. Hits turn 2. No charge in sunlight.","O"])
map.set("Sonic Boom",["Sonic Boom","Normal","—","90%","20","Always does 20 HP of damage.","O"])
map.set("Spark",["Spark","Electric","65","100%","20","30% chance to paralyze the target.","O"])
map.set("Spider Web",["Spider Web","Bug","—","—","10","Prevents the target from switching out.","O"])
map.set("Spike Cannon",["Spike Cannon","Normal","20","100%","15","Hits 2-5 times in one turn.","O"])
map.set("Spikes",["Spikes","Ground","—","—","20","Hurts grounded foes on switch-in. Max 3 layers.","O"])
map.set("Spit Up",["Spit Up","Normal","—","100%","10","More power with more uses of Stockpile.","O"])
map.set("Spite",["Spite","Ghost","—","100%","10","Lowers the PP of the target's last move by 2-5.","O"])
map.set("Splash",["Splash","Normal","—","—","40","No competitive use.","O"])
map.set("Spore",["Spore","Grass","—","100%","15","Causes the target to fall asleep.","O"])
map.set("Steel Wing",["Steel Wing","Steel","70","90%","25","10% chance to raise the user's Defense by 1.","O"])
map.set("Stockpile",["Stockpile","Normal","—","—","10","Raises user's Stockpile count by 1. Max 3 uses.","O"])
map.set("Stomp",["Stomp","Normal","65","100%","20","30% chance to make the target flinch.","O"])
map.set("Strength",["Strength","Normal","80","100%","15","No additional effect.","O"])
map.set("String Shot",["String Shot","Bug","—","95%","40","Lowers the foe(s) Speed by 1.","O"])
map.set("Struggle",["Struggle","Normal","50","100%","1","User loses 1/4 the HP lost by the target.","O"])
map.set("Stun Spore",["Stun Spore","Grass","—","75%","30","Paralyzes the target.","O"])
map.set("Submission",["Submission","Fighting","80","80%","25","Has 1/4 recoil.","O"])
map.set("Substitute",["Substitute","Normal","—","—","10","User takes 1/4 its max HP to put in a substitute.","O"])
map.set("Sunny Day",["Sunny Day","Fire","—","—","5","For 5 turns, intense sunlight powers Fire moves.","O"])
map.set("Super Fang",["Super Fang","Normal","—","90%","10","Does damage equal to 1/2 target's current HP.","O"])
map.set("Superpower",["Superpower","Fighting","120","100%","5","Lowers the user's Attack and Defense by 1.","O"])
map.set("Supersonic",["Supersonic","Normal","—","55%","20","Causes the target to become confused.","O"])
map.set("Surf",["Surf","Water","95","100%","15","Hits foes. Power doubles against Dive.","O"])
map.set("Swagger",["Swagger","Normal","—","90%","15","Raises the target's Attack by 2 and confuses it.","O"])
map.set("Swallow",["Swallow","Normal","—","—","10","Heals the user based on uses of Stockpile.","O"])
map.set("Sweet Kiss",["Sweet Kiss","Normal","—","75%","10","Causes the target to become confused.","O"])
map.set("Sweet Scent",["Sweet Scent","Normal","—","100%","20","Lowers the foe(s) evasiveness by 1.","O"])
map.set("Swift",["Swift","Normal","60","—","20","This move does not check accuracy. Hits foes.","O"])
map.set("Swords Dance",["Swords Dance","Normal","—","—","30","Raises the user's Attack by 2.","O"])
map.set("Synthesis",["Synthesis","Grass","—","—","5","Heals the user by a weather-dependent amount.","O"])
map.set("Tackle",["Tackle","Normal","35","95%","35","No additional effect.","O"])
map.set("Tail Glow",["Tail Glow","Bug","—","—","20","Raises the user's Sp. Atk by 2.","O"])
map.set("Tail Whip",["Tail Whip","Normal","—","100%","30","Lowers the foe(s) Defense by 1.","O"])
map.set("Take Down",["Take Down","Normal","90","85%","20","Has 1/4 recoil.","O"])
map.set("Taunt",["Taunt","Dark","—","100%","20","For 2 turns, the target can't use status moves.","O"])
map.set("Teeter Dance",["Teeter Dance","Normal","—","100%","20","Confuses adjacent Pokemon.","O"])
map.set("Teleport",["Teleport","Psychic","—","—","20","Fails when used.","O"])
map.set("Thief",["Thief","Dark","40","100%","10","If the user has no item, it steals the target's.","O"])
map.set("Thrash",["Thrash","Normal","90","100%","20","Lasts 2-3 turns. Confuses the user afterwards.","O"])
map.set("Thunder",["Thunder","Electric","120","70%","10","30% chance to paralyze. Can't miss in rain.","O"])
map.set("Thunder Punch",["Thunder Punch","Electric","75","100%","15","10% chance to paralyze the target.","O"])
map.set("Thunder Shock",["Thunder Shock","Electric","40","100%","30","10% chance to paralyze the target.","O"])
map.set("Thunder Wave",["Thunder Wave","Electric","—","100%","20","Paralyzes the target.","O"])
map.set("Thunderbolt",["Thunderbolt","Electric","95","100%","15","10% chance to paralyze the target.","O"])
map.set("Tickle",["Tickle","Normal","—","100%","20","Lowers the target's Attack and Defense by 1.","O"])
map.set("Torment",["Torment","Dark","—","100%","15","Target can't select the same move twice in a row.","O"])
map.set("Toxic",["Toxic","Poison","—","85%","10","Badly poisons the target.","O"])
map.set("Transform",["Transform","Normal","—","—","10","Copies target's stats, moves, types, and Ability.","O"])
map.set("Tri Attack",["Tri Attack","Normal","80","100%","10","20% chance to paralyze or burn or freeze target.","O"])
map.set("Trick",["Trick","Psychic","—","100%","10","User switches its held item with the target's.","O"])
map.set("Triple Kick",["Triple Kick","Fighting","10","90%","10","Hits 3 times. Each hit can miss, but power rises.","O"])
map.set("Twineedle",["Twineedle","Bug","25","100%","20","Hits 2 times. Each hit has 20% chance to poison.","O"])
map.set("Twister",["Twister","Dragon","40","100%","20","20% chance to make the foe(s) flinch.","O"])
map.set("Uproar",["Uproar","Normal","50","100%","10","Lasts 2-5 turns. Active Pokemon cannot sleep.","O"])
map.set("Vice Grip",["Vice Grip","Normal","55","100%","30","No additional effect.","O"])
map.set("Vine Whip",["Vine Whip","Grass","35","100%","10","No additional effect.","O"])
map.set("Vital Throw",["Vital Throw","Fighting","70","—","10","This move does not check accuracy. Goes last.","O"])
map.set("Volt Tackle",["Volt Tackle","Electric","120","100%","15","Has 1/3 recoil.","O"])
map.set("Water Gun",["Water Gun","Water","40","100%","25","No additional effect.","O"])
map.set("Water Pulse",["Water Pulse","Water","60","100%","20","20% chance to confuse the target.","O"])
map.set("Water Sport",["Water Sport","Water","—","—","15","Weakens Fire-type attacks to 1/2 their power.","O"])
map.set("Water Spout",["Water Spout","Water","150","100%","5","Less power as user's HP decreases. Hits foe(s).","O"])
map.set("Waterfall",["Waterfall","Water","80","100%","15","No additional effect.","O"])
map.set("Weather Ball",["Weather Ball","Normal","50","100%","10","Damage doubles and type varies during weather.","O"])
map.set("Whirlpool",["Whirlpool","Water","15","70%","15","Traps and damages the target for 2-5 turns.","O"])
map.set("Whirlwind",["Whirlwind","Normal","—","100%","20","Forces the target to switch to a random ally.","O"])
map.set("Will-O-Wisp",["Will-O-Wisp","Fire","—","75%","15","Burns the target.","O"])
map.set("Wing Attack",["Wing Attack","Flying","60","100%","35","No additional effect.","O"])
map.set("Wish",["Wish","Normal","—","—","10","Next turn, heals 50% of the recipient's max HP.","O"])
map.set("Withdraw",["Withdraw","Water","—","—","40","Raises the user's Defense by 1.","O"])
map.set("Wrap",["Wrap","Normal","15","85%","20","Traps and damages the target for 2-5 turns.","O"])
map.set("Yawn",["Yawn","Normal","—","—","10","Puts the target to sleep after 1 turn.","O"])
map.set("Zap Cannon",["Zap Cannon","Electric","100","50%","5","100% chance to paralyze the target.","O"])
for (const [key] of map) populate(key);